[theme]
primaryColor = "#C71585"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFF5F8"
textColor = "#262626"
font = "serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
toolbarMode = "minimal"
