[theme]
primaryColor = "#E1306C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FAFAFA"
textColor = "#262626"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

SUPABASE_URL = "https://ktvlhviikifcxbibxsas.supabase.co/rest/v1/"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dmxodmlpa2lmY3hiaWJ4c2FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAyMjMyOTYsImV4cCI6MjA5NTc5OTI5Nn0.gq5pCtvHcsdONOu6XblG-pALnt1cp1BIEh0UbH8yhdE"